steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - gcr.io/$PROJECT_ID/frontend:latest
      - '-t'
      - gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/frontend
options:
  logging: CLOUD_LOGGING_ONLY
